name: Solr Core Creation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-solr-schema:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Build Docker image
      run: docker build -t my_solr_image .

    - name: Run Docker container
      run: docker run -d -p 8983:8983 -v ./:/var/solr/data/configsets/adc --name adc my_solr_image

    - name: Create Solr core
      run: |
        sleep 30 # Give Solr some time to start
        docker exec adc solr create_core -c adc -d /var/solr/data/configsets/adc || exit 1

    - name: Test atomic update flow
      run: |
        chmod +x tests/test_atomic_update.sh
        ./tests/test_atomic_update.sh
